module: safe-maps
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: get_directions.app

libraries:
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
